services:
  reward-service-db:
    image: mongo:4.2
    container_name: reward_service_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongodata:/data/db
    ports:
      - '6000:6000'

  reward-service:
    build: .
    image: reward_service:latest
    container_name: reward_service_app
    depends_on:
      - reward-service-db
    ports:
      - '9092:9092'
    volumes:
      - ./Config.toml:/app/Config.toml
      - ./logs:/app/logs
    environment:
      BAL_CONFIG_FILES: /app/Config.toml
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB: ${MONGO_DB}
      MONGO_COLLECTION: ${MONGO_COLLECTION}

volumes:
  mongodata:
