version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: reward-service-mongodb
    restart: unless-stopped
    ports:
      - "27022:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - reward-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  reward-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reward-service-app
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: ${MONGO_PORT}
      MONGO_URL: ${MONGO_URL}
      MONGO_DB: ${MONGO_DB}
      MONGO_REWARD_COLLECTION: ${MONGO_REWARD_COLLECTION}
      MONGO_USER_REWARD_COLLECTION: ${MONGO_USER_REWARD_COLLECTION}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - reward-network
    volumes:
      - ./logs:/app/logs

volumes:
  mongodb_data:
    driver: local

networks:
  reward-network:
    driver: bridge
